import { Injectable } from '@nestjs/common';
import type { OAuthRegisteredClientsStore } from '@modelcontextprotocol/sdk/server/auth/clients.js';
import type { OAuthClientInformationFull } from '@modelcontextprotocol/sdk/shared/auth.js';
import { InvalidClientMetadataError } from '@modelcontextprotocol/sdk/server/auth/errors.js';
import { PrismaService } from '../prisma/prisma.service';
import { IdentityCipher } from '../common/identity-cipher';
import type { OAuthClient } from '@prisma/client';

/** AAD scope for `IdentityCipher` — see `OAuthClient.clientSecretSealed`'s doc comment. */
const CLIENT_SECRET_SCOPE = 'oauth-client-secret';

/**
 * The MCP SDK's view of client storage — backs `mcpAuthRouter`'s dynamic
 * registration (RFC 7591) and client lookup for every AS endpoint.
 *
 * `getClient` is also what `authenticateClient` (the SDK's own middleware,
 * used ahead of `/token` and `/revoke`) calls to check a confidential
 * client's secret, via a literal `===` — see `OAuthClient`'s doc comment for
 * why that secret is sealed rather than hashed.
 */
@Injectable()
export class RedinfoClientsStore implements OAuthRegisteredClientsStore {
  constructor(
    private readonly prisma: PrismaService,
    private readonly identityCipher: IdentityCipher,
  ) {}

  async getClient(clientId: string): Promise<OAuthClientInformationFull | undefined> {
    const row = await this.prisma.oAuthClient.findUnique({ where: { clientId } });
    if (!row || row.disabledAt) return undefined;
    return this.toClientInformation(row);
  }

  /**
   * Dynamic Client Registration — always issues a public, PKCE-only client
   * (see the plan's "open DCR + admin pre-registration" decision), no matter
   * what `token_endpoint_auth_method` the caller asked for. Every code this
   * store's clients redeem goes through `OAuthProviderService.authorize()`,
   * which requires a PKCE `code_challenge` on every request — that already
   * defeats the authorization-code-interception attack a `client_secret`
   * exists to mitigate, so there's no security value in minting one over an
   * *open*, unauthenticated endpoint. Several real assistants (Claude among
   * them) default to requesting `client_secret_basic`/`client_secret_post`
   * even though they're really a browser-redirect + PKCE client underneath;
   * silently downgrading them to public rather than rejecting them is what
   * lets DCR actually complete for those callers instead of forcing every
   * one of them through manual admin provisioning.
   *
   * `OAuthAdminClientsController` remains the path for a platform that
   * specifically *requires* a durable `client_secret` to function (Copilot
   * Studio, historically) — DCR never hands one out.
   *
   * `client.client_id`/`client_id_issued_at` are already generated by the
   * SDK's `clientRegistrationHandler` before this runs — see its comment on
   * `OAuthRegisteredClientsStore.registerClient`.
   */
  async registerClient(
    client: Omit<OAuthClientInformationFull, 'client_id' | 'client_id_issued_at'>,
  ): Promise<OAuthClientInformationFull> {
    if (!client.redirect_uris || client.redirect_uris.length === 0) {
      throw new InvalidClientMetadataError('At least one redirect_uri is required.');
    }

    const full: OAuthClientInformationFull = {
      ...(client as OAuthClientInformationFull),
      token_endpoint_auth_method: 'none',
      client_secret: undefined,
      client_secret_expires_at: undefined,
    };
    await this.prisma.oAuthClient.create({
      data: {
        clientId: full.client_id,
        clientName: full.client_name ?? full.client_id,
        redirectUris: full.redirect_uris,
        isDynamic: true,
        // No secret: DCR only ever issues public, PKCE-only clients here.
      },
    });

    return full;
  }

  private toClientInformation(row: OAuthClient): OAuthClientInformationFull {
    const secret = row.clientSecretSealed
      ? this.identityCipher.open<string>(CLIENT_SECRET_SCOPE, row.id, row.clientSecretSealed)
      : undefined;

    return {
      client_id: row.clientId,
      client_secret: secret,
      client_id_issued_at: Math.floor(row.createdAt.getTime() / 1000),
      redirect_uris: row.redirectUris,
      client_name: row.clientName,
      token_endpoint_auth_method: secret ? 'client_secret_post' : 'none',
      grant_types: ['authorization_code', 'refresh_token'],
      response_types: ['code'],
    };
  }
}
