import { Injectable } from '@nestjs/common';
import type { OAuthRegisteredClientsStore } from '@modelcontextprotocol/sdk/server/auth/clients.js';
import type { OAuthClientInformationFull } from '@modelcontextprotocol/sdk/shared/auth.js';
import { InvalidClientMetadataError } from '@modelcontextprotocol/sdk/server/auth/errors.js';
import { PrismaService } from '../prisma/prisma.service';
import { IdentityCipher } from '../common/identity-cipher';
import type { OAuthClient } from '@prisma/client';

/** AAD scope for `IdentityCipher` — see `OAuthClient.clientSecretSealed`'s doc comment. */
const CLIENT_SECRET_SCOPE = 'oauth-client-secret';

/**
 * The MCP SDK's view of client storage — backs `mcpAuthRouter`'s dynamic
 * registration (RFC 7591) and client lookup for every AS endpoint.
 *
 * `getClient` is also what `authenticateClient` (the SDK's own middleware,
 * used ahead of `/token` and `/revoke`) calls to check a confidential
 * client's secret, via a literal `===` — see `OAuthClient`'s doc comment for
 * why that secret is sealed rather than hashed.
 */
@Injectable()
export class RedinfoClientsStore implements OAuthRegisteredClientsStore {
  constructor(
    private readonly prisma: PrismaService,
    private readonly identityCipher: IdentityCipher,
  ) {}

  async getClient(clientId: string): Promise<OAuthClientInformationFull | undefined> {
    const row = await this.prisma.oAuthClient.findUnique({ where: { clientId } });
    if (!row || row.disabledAt) return undefined;
    return this.toClientInformation(row);
  }

  /**
   * Dynamic Client Registration — public clients only (see the plan's
   * "open DCR + admin pre-registration" decision). A confidential client
   * (Copilot Studio, typically) is provisioned instead through
   * `OAuthAdminClientsController`, never through this open endpoint.
   *
   * `client.client_id`/`client_id_issued_at` are already generated by the
   * SDK's `clientRegistrationHandler` before this runs — see its comment on
   * `OAuthRegisteredClientsStore.registerClient`. This method's job is only
   * to persist what it was handed and hand back the same shape.
   */
  async registerClient(
    client: Omit<OAuthClientInformationFull, 'client_id' | 'client_id_issued_at'>,
  ): Promise<OAuthClientInformationFull> {
    if (client.token_endpoint_auth_method && client.token_endpoint_auth_method !== 'none') {
      throw new InvalidClientMetadataError(
        'Dynamic client registration only supports public clients ' +
          '(token_endpoint_auth_method: "none"). A confidential client must be ' +
          'registered by a redinfo administrator.',
      );
    }
    if (!client.redirect_uris || client.redirect_uris.length === 0) {
      throw new InvalidClientMetadataError('At least one redirect_uri is required.');
    }

    const full = client as OAuthClientInformationFull;
    await this.prisma.oAuthClient.create({
      data: {
        clientId: full.client_id,
        clientName: full.client_name ?? full.client_id,
        redirectUris: full.redirect_uris,
        isDynamic: true,
        // No secret: DCR only ever issues public, PKCE-only clients here.
      },
    });

    return full;
  }

  private toClientInformation(row: OAuthClient): OAuthClientInformationFull {
    const secret = row.clientSecretSealed
      ? this.identityCipher.open<string>(CLIENT_SECRET_SCOPE, row.id, row.clientSecretSealed)
      : undefined;

    return {
      client_id: row.clientId,
      client_secret: secret,
      client_id_issued_at: Math.floor(row.createdAt.getTime() / 1000),
      redirect_uris: row.redirectUris,
      client_name: row.clientName,
      token_endpoint_auth_method: secret ? 'client_secret_post' : 'none',
      grant_types: ['authorization_code', 'refresh_token'],
      response_types: ['code'],
    };
  }
}
