apiVersion: v2
name: redinfo
description: A Helm chart for deploying the redinfo application (backend + frontend)
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: postgresql
    version: "12.3.0"
    repository: "https://charts.bitnami.com/bitnami"

