apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redinfo.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "redinfo.name" . }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "redinfo.name" . }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "redinfo.name" . }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - containerPort: 80
          {{- if or (and (kindIs "map" .Values.env.frontend) (gt (len .Values.env.frontend) 0)) (and (kindIs "slice" .Values.env.frontend) (gt (len .Values.env.frontend) 0)) }}
          env:
            {{- if kindIs "map" .Values.env.frontend }}
            {{- range $name, $value := .Values.env.frontend }}
            - name: {{ $name }}
              value: {{ $value | toString | quote }}
            {{- end }}
            {{- else if kindIs "slice" .Values.env.frontend }}
            {{- toYaml .Values.env.frontend | nindent 12 }}
            {{- end }}
          {{- end }}
          resources:
{{ toYaml .Values.resources.frontend | indent 12 }}
